Args = \
  --initialize-at-run-time=org.apache.commons.logging.LogFactory,\
  org.apache.commons.logging.LogFactoryService,\
  net.fortuna.ical4j.model.TimeZoneRegistryFactory,\
  net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory,\
  net.fortuna.ical4j.util.CompatibilityHints \
  --initialize-at-build-time=org.slf4j,ch.qos.logback \
  --enable-url-protocols=https,http \
  -H:+ReportExceptionStackTraces \
  -H:+AddAllCharsets
