runtime: java17
entrypoint: java -Dspring.profiles.active=prod -jar top-leader.jar
instance_class: B2
basic_scaling:
  max_instances: 1
env_variables:
  SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
  
handlers:
  - url: /*
    static_files: None
    upload: None
    http_headers:
      Access-Control-Allow-Origin: "*"